name: LateX CV to PDF

on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document 001
        id: compile-latex-document-001
        uses: ./
        with:
          output_dir: output
          main_latex_file: source/001/Section 1 Spring 2023.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos
      - name: Upload PDF to the workflow tab
        id: upload-workflow-001
        uses: actions/upload-artifact@v2
        with:
          name: output-fontawesome
          path: Section 1 Spring 2023.pdf
          
      - name: Compile LaTeX document 003
        id: compile-latex-document-003
        uses: ./
        with:
          output_dir: output
          main_latex_file: source/003/Section 3 Spring 2023.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos
          
      - name: Upload PDF to the workflow tab
        id: upload-workflow-003
        uses: actions/upload-artifact@v2
        with:
          name: output-fontawesome
          path: Section 3 Spring 2023.pdf
