name: LateX Syllabus to PDF

on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: Compile LaTeX document 001
        id: compile-latex-document-001
        uses: thomas-chauvet/latex2pdf-action@1.0.4
        with:
          output_dir: PDF
          main_latex_file: source/001/Section_001_Spring_2023.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos fullpage preprint
         
      - name: Upload PDF to the workflow tab
        id: upload-workflow-001
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: PDF/Section_001_Spring_2023.pdf
          
      - name: Compile LaTeX document 003
        id: compile-latex-document-003
        uses: thomas-chauvet/latex2pdf-action@1.0.4
        with:
          output_dir: PDF
          main_latex_file: source/003/Section_003_Spring_2023.tex
          ctan_packages: moderncv colortbl fontawesome lua-uni-algos fullpage preprint
          
      - name: Upload PDF to the workflow tab
        id: upload-workflow-003
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: PDF/Section_003_Spring_2023.pdf
          
      - name: Deploy back to gh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then git checkout "$GITHUB_HEAD_REF"; fi
          git config --local user.name "GitHub Actions"
          git config --local user.email "<>"
          git checkout main
          git merge main
          git add PDF/
          git commit -m 'GitHub Actions: build site' || echo 'nothing to commit'
          git push origin main || echo 'nothing to push'
